### PR TITLE
Increased error checking for embedding In/Out pointers

### LINKED ISSUE #131: Can't embed pointers to dig.In/Out
The following e2e test doesn't work:

```go
	t.Run("embedding out pointers works", func(t *testing.T) {
		c := New()
		type A struct{}
		type B struct {
			Out
			A
		}
		type C struct {
			*B // pointer to B which is a dig.In with A
		}
		require.NoError(t, c.Provide(func() C { return C{} }))
		require.NoError(t, c.Invoke(func(A) {}))
	})
```

It works if type C is written to embed type B directly, rather than the pointer to B:

```go
type C struct {
  B // direct embed of type B
}
```

Question is... do we care? `embedsType` function seems to solely focus on structs:

```go
if t.Kind() != reflect.Struct {
  continue
}
```

Should be easy to modify to look at `Elems()` of a pointer instead.

### PR DESCRIPTION
**Pull request by glibsm**
Well this sure is messy, but there is massive complexity in just how many cases there are:

- Embedding pointers to In/Out
- Using pointers as params/returns
- Embedding pointers to objects that embed In/Out
- Embedding pointers to objects that embed pointers to In/Out
- ????

I wrote some e2e tests that in general I expect to fail and pass and reversed it from there. This obviously adds some tech debt that should be cleaned up.

Fixes #131

### CODE REVIEW

File: dig_test.go [hunk 1]
```diff
@@ -883,17 +883,14 @@ func TestCantProvideParameterObjects(t *testing.T) {
...
-		c := New()
-		require.NoError(t, c.Provide(func() (*Args, error) {
-			return args, nil
-		}), "provide failed")
-		require.NoError(t, c.Invoke(func(a *Args) {
-			require.True(t, args == a, "args must match")
-		}), "invoke failed")
+		err := c.Provide(func() (*Args, error) { return args, nil })
+		require.Error(t, err)
+		assert.Contains(t, err.Error(), "can't provide pointers to parameter objects")
```
Comment (akshayjshah) [inline dig_test.go]: This test has somehow gotten weird - why are we writing test cases that *return* `fx.In`? I think that the intention was to test that we can write constructors that return pointers. If that's not covered elsewhere, let's add a test with a constructor that returns `*byte.Buffer`.

Separately, we should add whatever test we need for pointers to In/Out structs.

File: dig_test.go [hunk 2]
```diff
@@ -1081,6 +1078,33 @@ func TestProvideFailures(t *testing.T) {
...
+		c := New()
+
+		type out struct {
+			*Out
+
+			String string
+		}
+
+		err := c.Provide(func() out { return out{String: "foo"} })
+		fmt.Println(c)
```
Comment (akshayjshah) [inline dig_test.go]: Stray `println`.

File: types.go [hunk 3]
```diff
@@ -26,10 +26,12 @@ import (
...
-	_noValue reflect.Value
-	_errType = reflect.TypeOf((*error)(nil)).Elem()
-	_inType  = reflect.TypeOf((*In)(nil)).Elem()
-	_outType = reflect.TypeOf((*Out)(nil)).Elem()
+	_noValue    reflect.Value
+	_errType    = reflect.TypeOf((*error)(nil)).Elem()
+	_inPtrType  = reflect.TypeOf((*In)(nil))
+	_inType     = _inPtrType.Elem()
+	_outPtrType = reflect.TypeOf((*Out)(nil))
+	_outType    = _outPtrType.Elem()
```
Comment (akshayjshah) [inline types.go]: Perhaps clearer as `reflect.TypeOf(Out{})`?

**Comment by breerly** [comment]
You mention this takes on some debt - can you create `// TODO` comments everywhere you feel some ickiness has been introduced?

File: dig_test.go (hunk 1 above)
Comment (glibsm) [inline dig_test.go]: There are plenty of tests that cover the pointers, like `*byte.Buffer`. This tries to cover the mis-use case when `In` is used instead of `Out`.

I just modified the previous test.
